jobs:
- name: deploy-github-teams
  plan:
  - aggregate:
    - get: PGR301Organisation
      trigger: true
  - task: apply
    file: PGR301Organisation/concourse/tasks/terraform/task.yml
    input_mapping: {source: PGR301Organisation}
    params:
      github_token: ((github_token))
      command: apply
      directories: |
          .

resources:

- name: PGR301Organisation
  type: git
  source:
    uri: https://github.com/PGR301Organisation/frontend.git
    branch: master
